spring:
  profiles:
    active: home
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      format_sql: true
      use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: pmigaj@gmail.com
    password: vxuhexdnqdovqgkh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

application:
  default:
    newUserRole: ROLE_USER
    newDoctorRole: ROLE_DOCTOR
    roles:
      - ROLE_ADMIN
      - ROLE_USER
      - ROLE_DOCTOR
    users:
      - username: admin
        password: admin
        roles: ROLE_ADMIN,ROLE_USER,ROLE_DOCTOR
      - username: user
        password: user
        roles: ROLE_USER

